## provide the name of the namespace
namespace:
  name: helm-prod 

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: 1.17.0

resources:
  requests:
    cpu: 70m
    memory: 256Mi
    
## set the number of replicas for an application 
replicaCount: 2

service:
  port: 80
  type: ClusterIP

configmap:
  data: "version: 1.17.0"