## provide the name of the namespace
namespace:
  name: helm-staging

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: 1.18.0

resources:
  requests:
    cpu: 50m
    memory: 128Mi

## set the number of replicas for an application 
replicaCount: 1

configmap:
  data: "version: 1.18.0"