## provide the name of the namespace
namespace:
  name: demo-helm

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: alpine
  pull-policy: IfNotPresent

resources: CPU 50m and memory 256Mi

## set the number of replicas for an application 
replica:
  count: 3

service:
  type: ClusterIP
  port: 8111

configmap:
  data: "version: alpine"