## provide the name of the namespace
namespace:
  name: demo-helm

## define the image to execute with the Deployment 
image:
  repository: nginx 
  tag: alpine
  pull-policy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 256Mi

## set the number of replicas for an application 
replicaCount: 3

service:
  type: ClusterIP
  port: 8111

configmap:
  data: "version: alpine"